server:
  port: ${SERVER_PORT}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gorgany-microservices/configuration
          search-paths: /
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
